// flow-typed signature: 89f20c463f26b15f71fb565a092e134d
// flow-typed version: <<STUB>>/react-universal-component_vx.x.x/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-universal-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-universal-component' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-universal-component/dist/flowTypes' {
  declare module.exports: any
}

declare module 'react-universal-component/dist/index' {
  declare module.exports: any
}

declare module 'react-universal-component/dist/requireUniversalModule' {
  declare module.exports: any
}

declare module 'react-universal-component/dist/utils' {
  declare module.exports: any
}

declare module 'react-universal-component/server' {
  declare module.exports: any
}

// Filename aliases
declare module 'react-universal-component/dist/flowTypes.js' {
  declare module.exports: $Exports<'react-universal-component/dist/flowTypes'>
}
declare module 'react-universal-component/dist/index.js' {
  declare module.exports: $Exports<'react-universal-component/dist/index'>
}
declare module 'react-universal-component/dist/requireUniversalModule.js' {
  declare module.exports: $Exports<
    'react-universal-component/dist/requireUniversalModule',
  >
}
declare module 'react-universal-component/dist/utils.js' {
  declare module.exports: $Exports<'react-universal-component/dist/utils'>
}
declare module 'react-universal-component/server.js' {
  declare module.exports: $Exports<'react-universal-component/server'>
}
